#interface=wlan0mon
#driver=nl80211
#ssid=PrettyFly4AWiFi
#hw_mode=g
#channel=6
#macaddr_acl=0
#ignore_broadcast_ssid=0
#macaddr=

#wpa=2
#wpa_passphrase=""
#wpa_key_mgmt=WPA-PSK
#wpa_pairwise=TKIP
#rsn_pairwise=CCMP

interface=wlan0mon       # the interface used by the AP
hw_mode=a             # a simply means 5GHz
channel=0             # the channel to use, 0 means the AP will search for the channel with the least interferences 
#ieee80211d=1          # limit the frequencies used to those allowed in the country
#country_code=US       # the country code
ieee80211n=1          # 802.11n support
ieee80211ac=1         # 802.11ac support
wmm_enabled=1         # QoS support

ssid=xfinitywifi         # the name of the AP
#auth_algs=1           # 1=wpa, 2=wep, 3=both
#wpa=2                 # WPA2 only
#wpa_key_mgmt=WPA-PSK 
#rsn_pairwise=CCMP
#wpa_passphrase=somepassword
