#!/bin/bash

ser2net

ifup /dev/bleth0

airmon-ng

airmon-ng start bleth0

ifconfig bleth0 192.168.0.103 netmask 255.255.255.0
route add default gw 192.168.0.1
echo "nameserver 8.8.8.8" > /etc/resolv.conf



airmon-ng check kill

blctl set_auto_connect 1

blctl wifi_scan

blctl wifi_scan_results

blctl wifi_scan

blctl wifi_scan_results

blctl wifi_scan

blctl wifi_scan_results

blctl connect_ap rain blank21!

#sleep 30s

udhcpc -i bleth0

#udhcpc -i bleth0 &

blctl get_link_status
#udhcpc -i bleth0 &

