# add your custom package feeds here
#
src/gz Packages http://downloads.openwrt.org/snapshots/packages/riscv64_riscv64/packages
src/gz LuCi http://downloads.openwrt.org/snapshots/packages/riscv64_riscv64/luci
src/gz base http://downloads.openwrt.org/snapshots/packages/riscv64_riscv64/base
src/gz routing http://downloads.openwrt.org/snapshots/packages/riscv64_riscv64/routing
src/gz telephony http://downloads.openwrt.org/snapshots/packages/riscv64_riscv64/telephony
