#!/bin/sh


start() {

blctl set_auto_connect 1

blctl wifi_scan

blctl wifi_scan_results

blctl wifi_scan

blctl wifi_scan_results

blctl wifi_scan

blctl wifi_scan_results

blctl connect_ap rain blank21!

sleep 70s

udhcpc -i bleth0 &

}

case "$1" in
	start)
		"$1";;
	*)
		echo "Usage: $0 {start}"
		exit 1
esac
