#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/wifi

case "$1" in
  start)
        printf "Starting network: "
        blctl wifi_scan
        blctl wifi_scan_results
        blctl connect_ap rain blank21!
        sleep 70s

        udhcpc -i bleth0 &
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  stop)
#        printf "Stopping network: "
#       blctl wifi_scan
#        blctl wifi_scan_results
#        blctl connect_ap rain blank21!
#        sleep 70s
echo "Cool"
#        udhcpc -i bleth0 &
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?


